// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACzPly9QZyDOyu_CjfVaRtbB-W16qp9OY',
    appId: '1:191258108233:web:305919c170343fe99e7a98',
    messagingSenderId: '191258108233',
    projectId: 'ezybuy-72209',
    authDomain: 'ezybuy-72209.firebaseapp.com',
    storageBucket: 'ezybuy-72209.appspot.com',
    measurementId: 'G-ECFC7DTTJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJy3t4AyE-bJQ-XEtG9mdiTtQTSa-HFPE',
    appId: '1:191258108233:android:14696de3769021059e7a98',
    messagingSenderId: '191258108233',
    projectId: 'ezybuy-72209',
    storageBucket: 'ezybuy-72209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCoKBchgg8tGk1ucLssuh0IjQDJ2IVdIE',
    appId: '1:191258108233:ios:0c7970ebcfe504af9e7a98',
    messagingSenderId: '191258108233',
    projectId: 'ezybuy-72209',
    storageBucket: 'ezybuy-72209.appspot.com',
    iosBundleId: 'com.example.ezyBuyAdminn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCoKBchgg8tGk1ucLssuh0IjQDJ2IVdIE',
    appId: '1:191258108233:ios:c64dd3d32a972bdc9e7a98',
    messagingSenderId: '191258108233',
    projectId: 'ezybuy-72209',
    storageBucket: 'ezybuy-72209.appspot.com',
    iosBundleId: 'com.example.ezyBuyAdminn.RunnerTests',
  );
}
